export const STORAGE_KEYS = {
  auth: "auth",
  wallet: "wallet",
  onboardingDone: "onboarding_done",
} as const;

export const APP_ROUTES = {
  signin: "/signin",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  game: "/game",
  profile: "/profile",
  user: "/user",
  editProfile: "/edit-profile",
  wallet: "/wallet",
  depositMoney: "/deposit-money",
  getMoney: "/get-money",
  transfer: "/transfer",
  invite: "/invite",
  agentDeposit: "/agent-deposit",
  history: "/history",
  settings: "/settings",
  changePassword: "/change-password",
  language: "/language",
  activeSessions: "/active-sessions",
  leaderboard: "/leaderboard",
  tournament: "/tournament",
  missions: "/missions",
  notifications: "/notifications",
  dailyBonus: "/daily-bonus",
  walletHistory: "/wallet-history",
  withdrawalStatus: "/withdrawal-status",
  keno: "/keno",
  kenoPlay: "/keno/play",
  kenoHistory: "/keno/history",
  transaction: "/transaction",
  admin: {
    panel: "/admin/panel",
    users: "/admin/users",
    deposits: "/admin/deposits",
    withdrawals: "/admin/withdrawals",
    tournaments: "/admin/tournaments",
    missions: "/admin/missions",
    analytics: "/admin/analytics",
    agents: "/admin/agents",
  },
} as const;
